### ISSUE TITLE
hello elementor and WP Hotelier Integration

### ISSUE THREAD

**Issue by Shidaan2021** [wp-hotelier/wp-hotelier-hello-elementor#1]
I have installed the plugin numerous times but always get the same result:  
"Looks like you are using Hello Elementor without the official WP Hotelier integration. You can download the plugin for free [at this address](https://github.com/wp-hotelier/wp-hotelier-elementor/releases). Once you have downloaded the zip file, upload it to [Plugins > Add New](https://www.thecentralhotel.co.za/wp/wp-admin/plugin-install.php) like any other plugin."

**Comment by benitolopez** [comment]
Hello,

There is an error in the message. It should warn about the missing Hello theme.

You also need to install the Hello theme. That should be the displayed message.

To recap:

- install Elementor
- install Hello theme (this is required)
- install the integration

**Comment by Shidaan2021** [comment]
Hi Benito,
Thank you, that worked a charm.
All the best to you 
Shidaan

**Comment by hterminasyan** [comment]
> * Hello theme (

the plugin link looks broken, could you please kindly update it?

**Comment by benitolopez** [comment]
> > * Hello theme (
> 
> the plugin link looks broken, could you please kindly update it?

Where exactly?

**Comment by hterminasyan** [comment]
the repo of this link is not existing: **https://github.com/wp-hotelier/wp-hotelier-elementor/releases**

_You can download the plugin for free [at this address](https://github.com/wp-hotelier/wp-hotelier-elementor/releases) ....."_
