### ISSUE TITLE
not working on new elementor version

### ISSUE THREAD

**Issue by nechodom** [wp-hotelier/wp-hotelier-hello-elementor#2]
Hi, I have problem with your plugin. When I activate it, I cannot load Elementor. 

Here is log from Hotelier plugin:

![image](https://github.com/wp-hotelier/wp-hotelier-hello-elementor/assets/114414249/53f9c54c-81e5-4863-ba78-639bd3743478)

I have newest version of Elementor Pro.

Can you please look at it?
Thanks!

**Comment by benitolopez** [comment]
But what is not working exactly? Can you give me more details? Also, does it work with a previous version?
